#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         	1
bspc config window_gap           	5

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config top_padding		 2
bspc config bottom_padding	 2

bspc rule -a Chromium desktop='^2'
bspc rule -a discord desktop='^10' focus=off follow=false

$HOME/.config/polybar/launch.sh
#urxvt
